// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RisagerManagerServer.Models;

#nullable disable

namespace RisagerManagerServer.Migrations
{
    [DbContext(typeof(RisagerContext))]
    [Migration("20240712144226_AddBooking")]
    partial class AddBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RisagerManagerServer.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Arrival")
                        .HasColumnType("date");

                    b.Property<string>("BookingUserId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Departure")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BookingUserId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("RisagerManagerServer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RisagerManagerServer.Models.Booking", b =>
                {
                    b.HasOne("RisagerManagerServer.Models.User", "BookingUser")
                        .WithMany()
                        .HasForeignKey("BookingUserId");

                    b.Navigation("BookingUser");
                });
#pragma warning restore 612, 618
        }
    }
}
